language: python
python:
  - "2.7"
services:
  - "mysql"
  - "postgresql"
install: "pip install mysql-python psycopg2"
before_script:
  - cp test/travis.cfg test_drivers.cfg
  - mysql -e 'create database gauged;'
  - psql -c 'create database gauged;' -U postgres
script: make check
